#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
#
Name     : gpaste
Version  : 43.2
Release  : 27
URL      : https://github.com/Keruspe/GPaste/archive/v43.2/GPaste-43.2.tar.gz
Source0  : https://github.com/Keruspe/GPaste/archive/v43.2/GPaste-43.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: gpaste-bin = %{version}-%{release}
Requires: gpaste-data = %{version}-%{release}
Requires: gpaste-lib = %{version}-%{release}
Requires: gpaste-libexec = %{version}-%{release}
Requires: gpaste-license = %{version}-%{release}
Requires: gpaste-locales = %{version}-%{release}
Requires: gpaste-man = %{version}-%{release}
Requires: gpaste-services = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : desktop-file-utils
BuildRequires : gjs-dev
BuildRequires : mutter-dev
BuildRequires : pkgconfig(appstream-glib)
BuildRequires : pkgconfig(gcr-base-3)
BuildRequires : pkgconfig(gjs-1.0)
BuildRequires : pkgconfig(gnome-keybindings)
BuildRequires : pkgconfig(gtk4)
BuildRequires : pkgconfig(libadwaita-1)
BuildRequires : pkgconfig(systemd)
BuildRequires : vala
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<a href="https://scan.coverity.com/projects/gpaste">
<img alt="Coverity Scan Build Status"
src="https://scan.coverity.com/projects/6230/badge.svg"/>
</a>

%package bin
Summary: bin components for the gpaste package.
Group: Binaries
Requires: gpaste-data = %{version}-%{release}
Requires: gpaste-libexec = %{version}-%{release}
Requires: gpaste-license = %{version}-%{release}
Requires: gpaste-services = %{version}-%{release}

%description bin
bin components for the gpaste package.


%package data
Summary: data components for the gpaste package.
Group: Data

%description data
data components for the gpaste package.


%package dev
Summary: dev components for the gpaste package.
Group: Development
Requires: gpaste-lib = %{version}-%{release}
Requires: gpaste-bin = %{version}-%{release}
Requires: gpaste-data = %{version}-%{release}
Provides: gpaste-devel = %{version}-%{release}
Requires: gpaste = %{version}-%{release}

%description dev
dev components for the gpaste package.


%package lib
Summary: lib components for the gpaste package.
Group: Libraries
Requires: gpaste-data = %{version}-%{release}
Requires: gpaste-libexec = %{version}-%{release}
Requires: gpaste-license = %{version}-%{release}

%description lib
lib components for the gpaste package.


%package libexec
Summary: libexec components for the gpaste package.
Group: Default
Requires: gpaste-license = %{version}-%{release}

%description libexec
libexec components for the gpaste package.


%package license
Summary: license components for the gpaste package.
Group: Default

%description license
license components for the gpaste package.


%package locales
Summary: locales components for the gpaste package.
Group: Default

%description locales
locales components for the gpaste package.


%package man
Summary: man components for the gpaste package.
Group: Default

%description man
man components for the gpaste package.


%package services
Summary: services components for the gpaste package.
Group: Systemd services

%description services
services components for the gpaste package.


%prep
%setup -q -n GPaste-43.2
cd %{_builddir}/GPaste-43.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1679408780
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gpaste
cp %{_builddir}/GPaste-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gpaste/ab87eca3b439115109870f78ef594fae5a07e242 || :
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang GPaste

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gpaste-client

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GPaste-2.typelib
/usr/lib64/girepository-1.0/GPasteGtk-3.typelib
/usr/lib64/girepository-1.0/GPasteGtk-4.typelib
/usr/share/applications/org.gnome.GPaste.Preferences.desktop
/usr/share/applications/org.gnome.GPaste.Ui.desktop
/usr/share/bash-completion/completions/gpaste-client
/usr/share/dbus-1/services/org.gnome.GPaste.Preferences.service
/usr/share/dbus-1/services/org.gnome.GPaste.Ui.service
/usr/share/dbus-1/services/org.gnome.GPaste.service
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.GPaste.gschema.xml
/usr/share/gnome-control-center/keybindings/42-gpaste.xml
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/aboutItem.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/actionButtonActor.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/checkerBypass.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/deleteButton.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/deleteItemPart.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/dummyHistoryItem.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/emptyHistoryItem.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/extension.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/indicator.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/metadata.json
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/pageItem.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/pageSwitcher.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/prefs.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/searchItem.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/stateSwitch.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/statusIcon.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/uiItem.js
/usr/share/gnome-shell/search-providers/org.gnome.GPaste.search-provider.ini
/usr/share/metainfo/org.gnome.GPaste.Ui.appdata.xml
/usr/share/vala/vapi/gpaste-2.deps
/usr/share/vala/vapi/gpaste-2.vapi
/usr/share/vala/vapi/gpaste-gtk-3.deps
/usr/share/vala/vapi/gpaste-gtk-3.vapi
/usr/share/vala/vapi/gpaste-gtk-4.deps
/usr/share/vala/vapi/gpaste-gtk-4.vapi
/usr/share/zsh/site-functions/_gpaste-client

%files dev
%defattr(-,root,root,-)
/usr/include/gpaste-2/gpaste-gtk3.h
/usr/include/gpaste-2/gpaste-gtk3/gpaste-gtk-macros.h
/usr/include/gpaste-2/gpaste-gtk3/gpaste-gtk-settings-ui-panel.h
/usr/include/gpaste-2/gpaste-gtk3/gpaste-gtk-settings-ui-stack.h
/usr/include/gpaste-2/gpaste-gtk3/gpaste-gtk-settings-ui-widget.h
/usr/include/gpaste-2/gpaste-gtk3/gpaste-gtk-util.h
/usr/include/gpaste-2/gpaste-gtk4.h
/usr/include/gpaste-2/gpaste-gtk4/gpaste-gtk-macros.h
/usr/include/gpaste-2/gpaste-gtk4/gpaste-gtk-preferences-behaviour-page.h
/usr/include/gpaste-2/gpaste-gtk4/gpaste-gtk-preferences-group.h
/usr/include/gpaste-2/gpaste-gtk4/gpaste-gtk-preferences-history-settings-page.h
/usr/include/gpaste-2/gpaste-gtk4/gpaste-gtk-preferences-manager.h
/usr/include/gpaste-2/gpaste-gtk4/gpaste-gtk-preferences-page.h
/usr/include/gpaste-2/gpaste-gtk4/gpaste-gtk-preferences-shortcuts-page.h
/usr/include/gpaste-2/gpaste-gtk4/gpaste-gtk-preferences-widget.h
/usr/include/gpaste-2/gpaste-gtk4/gpaste-gtk-preferences-window.h
/usr/include/gpaste-2/gpaste-gtk4/gpaste-gtk-util.h
/usr/include/gpaste-2/gpaste.h
/usr/include/gpaste-2/gpaste/gpaste-client-item.h
/usr/include/gpaste-2/gpaste/gpaste-client.h
/usr/include/gpaste-2/gpaste/gpaste-gdbus-defines.h
/usr/include/gpaste-2/gpaste/gpaste-gdbus-macros.h
/usr/include/gpaste-2/gpaste/gpaste-gnome-shell-client.h
/usr/include/gpaste-2/gpaste/gpaste-gsettings-keys.h
/usr/include/gpaste-2/gpaste/gpaste-item-enums.h
/usr/include/gpaste-2/gpaste/gpaste-macros.h
/usr/include/gpaste-2/gpaste/gpaste-screensaver-client.h
/usr/include/gpaste-2/gpaste/gpaste-settings.h
/usr/include/gpaste-2/gpaste/gpaste-update-enums.h
/usr/include/gpaste-2/gpaste/gpaste-util.h
/usr/lib64/libgpaste-2.so
/usr/lib64/libgpaste-gtk-3.so
/usr/lib64/libgpaste-gtk4.so
/usr/lib64/pkgconfig/gpaste-2.pc
/usr/lib64/pkgconfig/gpaste-gtk-3.pc
/usr/lib64/pkgconfig/gpaste-gtk-4.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgpaste-2.so.0
/usr/lib64/libgpaste-2.so.0.0.1
/usr/lib64/libgpaste-gtk-3.so.0
/usr/lib64/libgpaste-gtk-3.so.0.0.1
/usr/lib64/libgpaste-gtk4.so.0
/usr/lib64/libgpaste-gtk4.so.0.0.1

%files libexec
%defattr(-,root,root,-)
/usr/libexec/gpaste/gpaste-daemon
/usr/libexec/gpaste/gpaste-preferences
/usr/libexec/gpaste/gpaste-ui

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gpaste/ab87eca3b439115109870f78ef594fae5a07e242

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gpaste-client.1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/org.gnome.GPaste.Preferences.service
/usr/lib/systemd/user/org.gnome.GPaste.Ui.service
/usr/lib/systemd/user/org.gnome.GPaste.service

%files locales -f GPaste.lang
%defattr(-,root,root,-)

