#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gpaste
Version  : 3.38.5
Release  : 10
URL      : https://github.com/Keruspe/GPaste/archive/v3.38.5/GPaste-3.38.5.tar.gz
Source0  : https://github.com/Keruspe/GPaste/archive/v3.38.5/GPaste-3.38.5.tar.gz
Summary  : Library to handle and communicate with GPaste
Group    : Development/Tools
License  : BSD-2-Clause
Requires: gpaste-bin = %{version}-%{release}
Requires: gpaste-data = %{version}-%{release}
Requires: gpaste-lib = %{version}-%{release}
Requires: gpaste-libexec = %{version}-%{release}
Requires: gpaste-license = %{version}-%{release}
Requires: gpaste-locales = %{version}-%{release}
Requires: gpaste-man = %{version}-%{release}
Requires: gpaste-services = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : gettext
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(appstream-glib)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gjs-1.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gnome-keybindings)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(mutter-clutter-7)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xi)
BuildRequires : sed
BuildRequires : vala

%description
<a href="https://scan.coverity.com/projects/gpaste">
<img alt="Coverity Scan Build Status"
src="https://scan.coverity.com/projects/6230/badge.svg"/>
</a>

%package bin
Summary: bin components for the gpaste package.
Group: Binaries
Requires: gpaste-data = %{version}-%{release}
Requires: gpaste-libexec = %{version}-%{release}
Requires: gpaste-license = %{version}-%{release}
Requires: gpaste-services = %{version}-%{release}

%description bin
bin components for the gpaste package.


%package data
Summary: data components for the gpaste package.
Group: Data

%description data
data components for the gpaste package.


%package dev
Summary: dev components for the gpaste package.
Group: Development
Requires: gpaste-lib = %{version}-%{release}
Requires: gpaste-bin = %{version}-%{release}
Requires: gpaste-data = %{version}-%{release}
Provides: gpaste-devel = %{version}-%{release}
Requires: gpaste = %{version}-%{release}

%description dev
dev components for the gpaste package.


%package lib
Summary: lib components for the gpaste package.
Group: Libraries
Requires: gpaste-data = %{version}-%{release}
Requires: gpaste-libexec = %{version}-%{release}
Requires: gpaste-license = %{version}-%{release}

%description lib
lib components for the gpaste package.


%package libexec
Summary: libexec components for the gpaste package.
Group: Default
Requires: gpaste-license = %{version}-%{release}

%description libexec
libexec components for the gpaste package.


%package license
Summary: license components for the gpaste package.
Group: Default

%description license
license components for the gpaste package.


%package locales
Summary: locales components for the gpaste package.
Group: Default

%description locales
locales components for the gpaste package.


%package man
Summary: man components for the gpaste package.
Group: Default

%description man
man components for the gpaste package.


%package services
Summary: services components for the gpaste package.
Group: Systemd services

%description services
services components for the gpaste package.


%prep
%setup -q -n GPaste-3.38.5
cd %{_builddir}/GPaste-3.38.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1612367879
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gpaste
cp %{_builddir}/GPaste-3.38.5/COPYING %{buildroot}/usr/share/package-licenses/gpaste/ab87eca3b439115109870f78ef594fae5a07e242
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang GPaste

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gpaste-client

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GPaste-1.0.typelib
/usr/share/applications/org.gnome.GPaste.Ui.desktop
/usr/share/bash-completion/completions/gpaste-client
/usr/share/dbus-1/services/org.gnome.GPaste.Ui.service
/usr/share/dbus-1/services/org.gnome.GPaste.service
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.GPaste.gschema.xml
/usr/share/gnome-control-center/keybindings/42-gpaste.xml
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/aboutItem.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/deleteButton.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/deleteItemPart.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/dummyHistoryItem.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/emptyHistoryItem.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/extension.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/indicator.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/metadata.json
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/pageItem.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/pageSwitcher.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/prefs.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/searchItem.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/stateSwitch.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/statusIcon.js
/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/uiItem.js
/usr/share/gnome-shell/search-providers/org.gnome.GPaste.search-provider.ini
/usr/share/metainfo/org.gnome.GPaste.Ui.appdata.xml
/usr/share/vala/vapi/gpaste-1.0.deps
/usr/share/vala/vapi/gpaste-1.0.vapi
/usr/share/zsh/site-functions/_gpaste-client

%files dev
%defattr(-,root,root,-)
/usr/include/gpaste/gpaste-bus-object.h
/usr/include/gpaste/gpaste-bus.h
/usr/include/gpaste/gpaste-client-item.h
/usr/include/gpaste/gpaste-client.h
/usr/include/gpaste/gpaste-clipboard.h
/usr/include/gpaste/gpaste-clipboards-manager.h
/usr/include/gpaste/gpaste-daemon.h
/usr/include/gpaste/gpaste-file-backend.h
/usr/include/gpaste/gpaste-gdbus-defines.h
/usr/include/gpaste/gpaste-gnome-shell-client.h
/usr/include/gpaste/gpaste-gsettings-keys.h
/usr/include/gpaste/gpaste-history.h
/usr/include/gpaste/gpaste-image-item.h
/usr/include/gpaste/gpaste-item-enums.h
/usr/include/gpaste/gpaste-item.h
/usr/include/gpaste/gpaste-keybinder.h
/usr/include/gpaste/gpaste-keybinding.h
/usr/include/gpaste/gpaste-macros.h
/usr/include/gpaste/gpaste-make-password-keybinding.h
/usr/include/gpaste/gpaste-password-item.h
/usr/include/gpaste/gpaste-pop-keybinding.h
/usr/include/gpaste/gpaste-screensaver-client.h
/usr/include/gpaste/gpaste-search-provider.h
/usr/include/gpaste/gpaste-settings-ui-panel.h
/usr/include/gpaste/gpaste-settings-ui-stack.h
/usr/include/gpaste/gpaste-settings-ui-widget.h
/usr/include/gpaste/gpaste-settings.h
/usr/include/gpaste/gpaste-show-history-keybinding.h
/usr/include/gpaste/gpaste-special-atom.h
/usr/include/gpaste/gpaste-storage-backend.h
/usr/include/gpaste/gpaste-sync-clipboard-to-primary-keybinding.h
/usr/include/gpaste/gpaste-sync-primary-to-clipboard-keybinding.h
/usr/include/gpaste/gpaste-text-item.h
/usr/include/gpaste/gpaste-ui-about.h
/usr/include/gpaste/gpaste-ui-backup-history.h
/usr/include/gpaste/gpaste-ui-delete-history.h
/usr/include/gpaste/gpaste-ui-delete-item.h
/usr/include/gpaste/gpaste-ui-edit-item.h
/usr/include/gpaste/gpaste-ui-empty-history.h
/usr/include/gpaste/gpaste-ui-empty-item.h
/usr/include/gpaste/gpaste-ui-header.h
/usr/include/gpaste/gpaste-ui-history-action.h
/usr/include/gpaste/gpaste-ui-history-actions.h
/usr/include/gpaste/gpaste-ui-history.h
/usr/include/gpaste/gpaste-ui-item-action.h
/usr/include/gpaste/gpaste-ui-item-skeleton.h
/usr/include/gpaste/gpaste-ui-item.h
/usr/include/gpaste/gpaste-ui-keybinding.h
/usr/include/gpaste/gpaste-ui-new-item.h
/usr/include/gpaste/gpaste-ui-panel-history.h
/usr/include/gpaste/gpaste-ui-panel.h
/usr/include/gpaste/gpaste-ui-reexec.h
/usr/include/gpaste/gpaste-ui-search-bar.h
/usr/include/gpaste/gpaste-ui-search.h
/usr/include/gpaste/gpaste-ui-settings.h
/usr/include/gpaste/gpaste-ui-shortcuts-window.h
/usr/include/gpaste/gpaste-ui-switch.h
/usr/include/gpaste/gpaste-ui-upload-item.h
/usr/include/gpaste/gpaste-ui-window.h
/usr/include/gpaste/gpaste-update-enums.h
/usr/include/gpaste/gpaste-upload-keybinding.h
/usr/include/gpaste/gpaste-uris-item.h
/usr/include/gpaste/gpaste-util.h
/usr/include/gpaste/gpaste.h
/usr/lib64/libgpaste.so
/usr/lib64/pkgconfig/gpaste-1.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgpaste.so.13
/usr/lib64/libgpaste.so.13.0.2

%files libexec
%defattr(-,root,root,-)
/usr/libexec/gpaste/gpaste-daemon
/usr/libexec/gpaste/gpaste-ui

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gpaste/ab87eca3b439115109870f78ef594fae5a07e242

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gpaste-client.1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/org.gnome.GPaste.Ui.service
/usr/lib/systemd/user/org.gnome.GPaste.service

%files locales -f GPaste.lang
%defattr(-,root,root,-)

